//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Microsoft.Live.Safety.Tools.VRAS {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("VRASConfiguration", Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd", IsNullable=false)]
    public partial class VRASConfigurationType {
        
        private GlobalSettings settingsField;
        
        private BatchType[] batchField;
        
        /// <remarks/>
        public GlobalSettings Settings {
            get {
                return this.settingsField;
            }
            set {
                this.settingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Batch")]
        public BatchType[] Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class GlobalSettings {
        
        private SettingThatAreOverridableType globalOverridableSettingsField;
        
        private string eventSourceField;
        
        private string serviceStopTimeOutSecField;
        
        private string errorLogPathField;
        
        private string regExMatchNotFoundDefaultStringField;
        
        /// <remarks/>
        public SettingThatAreOverridableType GlobalOverridableSettings {
            get {
                return this.globalOverridableSettingsField;
            }
            set {
                this.globalOverridableSettingsField = value;
            }
        }
        
        /// <remarks/>
        public string EventSource {
            get {
                return this.eventSourceField;
            }
            set {
                this.eventSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ServiceStopTimeOutSec {
            get {
                return this.serviceStopTimeOutSecField;
            }
            set {
                this.serviceStopTimeOutSecField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorLogPath {
            get {
                return this.errorLogPathField;
            }
            set {
                this.errorLogPathField = value;
            }
        }
        
        /// <remarks/>
        public string RegExMatchNotFoundDefaultString {
            get {
                return this.regExMatchNotFoundDefaultStringField;
            }
            set {
                this.regExMatchNotFoundDefaultStringField = value;
            }
        }

        public string TempFileExt { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class SettingThatAreOverridableType {
        
        private string newFileDelaySecondsField;
        
        private bool deleteAfterCopyField;
        
        private bool copyZeroByteFilesField;
        
        private string copyThreadPerSourceField;
        
        private string sleepBetweenBatchesMsField;
        
        private bool copyFromFirstDestinationDirField;
        
        private string copyRetryCountField;
        
        private string retrySleepMsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NewFileDelaySeconds {
            get {
                return this.newFileDelaySecondsField;
            }
            set {
                this.newFileDelaySecondsField = value;
            }
        }
        
        /// <remarks/>
        public bool DeleteAfterCopy {
            get {
                return this.deleteAfterCopyField;
            }
            set {
                this.deleteAfterCopyField = value;
            }
        }
        
        /// <remarks/>
        public bool CopyZeroByteFiles {
            get {
                return this.copyZeroByteFilesField;
            }
            set {
                this.copyZeroByteFilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CopyThreadPerSource {
            get {
                return this.copyThreadPerSourceField;
            }
            set {
                this.copyThreadPerSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SleepBetweenBatchesMs {
            get {
                return this.sleepBetweenBatchesMsField;
            }
            set {
                this.sleepBetweenBatchesMsField = value;
            }
        }
        
        /// <remarks/>
        public bool CopyFromFirstDestinationDir {
            get {
                return this.copyFromFirstDestinationDirField;
            }
            set {
                this.copyFromFirstDestinationDirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string CopyRetryCount {
            get {
                return this.copyRetryCountField;
            }
            set {
                this.copyRetryCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string RetrySleepMs {
            get {
                return this.retrySleepMsField;
            }
            set {
                this.retrySleepMsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class ArchiveType {
        
        private ArchiveTypeArchiveOption archiveOptionField;
        
        private string archiveOptionValueField;
        
        /// <remarks/>
        public ArchiveTypeArchiveOption ArchiveOption {
            get {
                return this.archiveOptionField;
            }
            set {
                this.archiveOptionField = value;
            }
        }
        
        /// <remarks/>
        public string ArchiveOptionValue {
            get {
                return this.archiveOptionValueField;
            }
            set {
                this.archiveOptionValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public enum ArchiveTypeArchiveOption {
        
        /// <remarks/>
        RegExOnFileName,
        
        /// <remarks/>
        FileTimeLastModifyTime,
        
        /// <remarks/>
        FileTimeDateCreatedTime,
        
        /// <remarks/>
        FileTimeLastModifyTimeUtc,
        
        /// <remarks/>
        FileTimeDateCreatedTimeUtc,
        
        /// <remarks/>
        StaticName,
        
        /// <remarks/>
        CopySetName,
        
        /// <remarks/>
        RegExOnFilePath,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class ArchiveLineType {
        
        private string tierField;
        
        private ArchiveType optionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Tier {
            get {
                return this.tierField;
            }
            set {
                this.tierField = value;
            }
        }
        
        /// <remarks/>
        public ArchiveType Option {
            get {
                return this.optionField;
            }
            set {
                this.optionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class ArchiveFeatureType {
        
        private bool archiveFeatureEnabledField;
        
        private ArchiveLineType[] archiveLinesField;
        
        /// <remarks/>
        public bool ArchiveFeatureEnabled {
            get {
                return this.archiveFeatureEnabledField;
            }
            set {
                this.archiveFeatureEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ArchiveLines")]
        public ArchiveLineType[] ArchiveLines {
            get {
                return this.archiveLinesField;
            }
            set {
                this.archiveLinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class DestinationType {
        
        private string destinationLocationField;
        
        private bool hashCompareFlagField;
        
        private ArchiveFeatureType archiveSettingsField;
        
        /// <remarks/>
        public string DestinationLocation {
            get {
                return this.destinationLocationField;
            }
            set {
                this.destinationLocationField = value;
            }
        }
        
        /// <remarks/>
        public bool HashCompareFlag {
            get {
                return this.hashCompareFlagField;
            }
            set {
                this.hashCompareFlagField = value;
            }
        }
        
        /// <remarks/>
        public ArchiveFeatureType ArchiveSettings {
            get {
                return this.archiveSettingsField;
            }
            set {
                this.archiveSettingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class SourceType {
        
        private string sourceFolderPathField;
        
        private SettingThatAreOverridableType sourceSettingOverridesField;
        
        private string fileRegExFilterField;
        
        private string folderRegExFilterField;
        
        private SourceTypeCopyType copyTypeField;
        
        /// <remarks/>
        public string SourceFolderPath {
            get {
                return this.sourceFolderPathField;
            }
            set {
                this.sourceFolderPathField = value;
            }
        }
        
        /// <remarks/>
        public SettingThatAreOverridableType SourceSettingOverrides {
            get {
                return this.sourceSettingOverridesField;
            }
            set {
                this.sourceSettingOverridesField = value;
            }
        }
        
        /// <remarks/>
        public string FileRegExFilter {
            get {
                return this.fileRegExFilterField;
            }
            set {
                this.fileRegExFilterField = value;
            }
        }
        
        /// <remarks/>
        public string FolderRegExFilter {
            get {
                return this.folderRegExFilterField;
            }
            set {
                this.folderRegExFilterField = value;
            }
        }
        
        /// <remarks/>
        public SourceTypeCopyType CopyType {
            get {
                return this.copyTypeField;
            }
            set {
                this.copyTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public enum SourceTypeCopyType {
        
        /// <remarks/>
        Root,
        
        /// <remarks/>
        Mirror,
        
        /// <remarks/>
        CombineToRoot,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class CopyJobOptionsType {
        
        private SourceType[] sourceFolderField;
        
        private DestinationType[] destinationFolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SourceFolder")]
        public SourceType[] SourceFolder {
            get {
                return this.sourceFolderField;
            }
            set {
                this.sourceFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DestinationFolder")]
        public DestinationType[] DestinationFolder {
            get {
                return this.destinationFolderField;
            }
            set {
                this.destinationFolderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class CopyJobsType {
        
        private CopyJobOptionsType copyCollectionField;
        
        /// <remarks/>
        public CopyJobOptionsType CopyCollection {
            get {
                return this.copyCollectionField;
            }
            set {
                this.copyCollectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class BatchSettingsType {
        
        private string batchNameField;
        
        private SettingThatAreOverridableType batchSettingOverridesField;
        
        /// <remarks/>
        public string BatchName {
            get {
                return this.batchNameField;
            }
            set {
                this.batchNameField = value;
            }
        }
        
        /// <remarks/>
        public SettingThatAreOverridableType BatchSettingOverrides {
            get {
                return this.batchSettingOverridesField;
            }
            set {
                this.batchSettingOverridesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/WindowsLive/Safety/VRAS.xsd")]
    public partial class BatchType {
        
        private BatchSettingsType batchSettingsField;
        
        private CopyJobsType copyCollectionField;
        
        /// <remarks/>
        public BatchSettingsType BatchSettings {
            get {
                return this.batchSettingsField;
            }
            set {
                this.batchSettingsField = value;
            }
        }
        
        /// <remarks/>
        public CopyJobsType CopyCollection {
            get {
                return this.copyCollectionField;
            }
            set {
                this.copyCollectionField = value;
            }
        }
    }
}
